[agent]
  interval = "2s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb3:8181"]
  token = "${TC_INFLUXDB_ADMIN_TOKEN}"
  organization = "${TC_INFLUXDB_ORG}"
  bucket = "${TC_INFLUXDB_BUCKET}"

[[inputs.kafka_consumer]]
  brokers = ["${TC_KAFKA_BOOTSTRAP_SERVERS_INTERNAL}"]
  topic_regexps = ["^statistics_.*$"]
  topic_tag = "kafka_topic"
  metadata_refresh_interval = "30s"
  data_format = "json"
  name_override = "zone_events"

  tag_keys = ["camera_id", "class", "direction"]

  json_time_key = "timestamp"
  json_time_format = "unix"