# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .

# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  save_video : False

#--------------------------------------------------GENERAL--------------------------------------------------

general:
  colors_of_zones: # in bgr
    1: [0,255,0] #green
    2: [255,0,0] #red

# ------------------------------------------------- NODES --------------------------------------------------
video_reader:
  src: ${oc.env:VIDEO_SRC} # path to file

  

tracking_node:  
  # first_track_thresh: 0.5  # Пороговое значение для первичной инициализации трека
  # second_track_thresh: 0.10  # Пороговое значение для поддержания трека
  # match_thresh: 0.95  # Чем больше значение, тем больше может быть расстояние между соседними обнаруженими чтобы держать трек
  # track_buffer: 125  # Время жизни трека после исчезновения из поля зрения (измеряется в числе кадров)


show_node:
  # scale : 0.6  # Масштабирование итогового окна результатов при imshow=True
  # imshow: False  # Нужно ли выводить видео в процессе обработки
  # fps_counter_N_frames_stat : 15  # Окно усредения fsp счетчика
  # draw_fps_info : True  # Указывать ли fps обработки
  # show_roi: True  # Показывать ли регионы примыкающих дорог 
  # overlay_transparent_mask: False # Заливка регионов при show_roi=True (медленная операция)
  # show_only_yolo_detections : False  # Отображать лишь результаты детекции без учета трекинга и прочей логики кода
  # show_track_id_different_colors: False  # Отображать цвет бокса согласно id трека, а не логике прибытия объекта
  # show_info_statistics: False  # Вывод информации о статистике в отдельном окне справа от кадра
