# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .

# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  save_video : False

#--------------------------------------------------GENERAL--------------------------------------------------

general:
  zones: "configs/zones.json" #json with in-out zones of road
  roi: "configs/roi.json"
# ------------------------------------------------- NODES --------------------------------------------------
video_reader:
  src: "data/night.mp4" # path to file
  skip_time: "0" #how much time delay beetwen frames in ms
  


detection_node:
  weight_path: weights/yolo11n.pt
  classes_to_detect: [2,3,5,7]  # all transport YOLO
  confidence: 0.40  # than more value less find
  iou: 0.7  # NMS more values more find
  imgsz: 640  # default value
  only_roi_area_detect: True


tracking_node:  
  first_track_thresh: 0.5  # Пороговое значение для первичной инициализации трека
  second_track_thresh: 0.60  # Пороговое значение для поддержания трека
  match_thresh: 0.95  # Чем больше значение, тем больше может быть расстояние между соседними обнаруженими чтобы держать трек
  track_buffer: 125  # Время жизни трека после исчезновения из поля зрения (измеряется в числе кадров)


show_node:
  scale : 1 # Scale for imshow=True
  imshow: True  # open imshow windows?
  fps_window_N_frames : 15  # lap for average frames
  show_fps : True  
  show_roi_border: True  # show borders of roi. its not zones
  show_roi_detector_border: True  # show borders of roi detector. its some small than roi_border
  show_zones: True #show borders zones
  show_only_yolo_detection: False
  fontFace: "1"
  fontScale : "2"
  thickness : "2"

  # show_fill_zones: False # Fill zones with colors NO NEED MAY BE

  # show_only_yolo_detections : False  # Отображать лишь результаты детекции без учета трекинга и прочей логики кода
  # show_track_id_different_colors: False  # Отображать цвет бокса согласно id трека, а не логике прибытия объекта
  # show_info_statistics: False  # Вывод информации о статистике в отдельном окне справа от кадра
